# Generated by Django 5.2.1 on 2025-05-19 09:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(default='Desconocido', max_length=100)),
                ('doc_identity', models.CharField(default='00000000', max_length=20)),
                ('phone', models.CharField(default='0000000000', max_length=10)),
                ('address', models.CharField(default='Dirección desconocida', max_length=255)),
                ('licence_drive', models.CharField(default='SIN LICENCIA', max_length=30)),
                ('date_entry', models.DateField(default=django.utils.timezone.now)),
                ('state', models.IntegerField(choices=[(0, 'No disponible'), (1, 'Disponible'), (2, 'Suspendido')], default=1)),
            ],
            options={
                'db_table': 'conductor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'tipo_mantenimiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'tipo_vehiculo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('id_rol', models.IntegerField(choices=[(1, 'Conductor'), (2, 'Tecnico'), (3, 'Admin')])),
                ('state', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Pendiente'), (4, 'Suspendido')], default=1)),
                ('last_date_support', models.DateField(blank=True, null=True)),
                ('next_date_support', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('marca', models.CharField(max_length=25)),
                ('modelo', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('state', models.IntegerField(choices=[(1, 'Nuevo'), (2, 'Deteriorado'), (3, 'Usado'), (4, 'Reparado')], default=1)),
                ('current_kilometers', models.FloatField(default=0)),
                ('last_date_support', models.DateField(blank=True, null=True)),
                ('next_date_support', models.DateField(blank=True, null=True)),
                ('id_tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vehiculos', to='app.tipovehiculo')),
            ],
            options={
                'db_table': 'vehiculo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServicioMantenimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='servicios_mantenimiento', to='app.vehiculo')),
            ],
            options={
                'db_table': 'servicio_mantenimiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('kilometraje', models.FloatField()),
                ('costo', models.FloatField()),
                ('workshop', models.CharField(max_length=100)),
                ('tipo', models.IntegerField(choices=[(1, 'Preventivo'), (2, 'Correctivo'), (3, 'General')], default=1)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('km_programado', models.FloatField(blank=True, null=True)),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mantenimientos', to='app.vehiculo')),
            ],
            options={
                'db_table': 'mantenimiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMantenimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.mantenimiento')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.serviciomantenimiento')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_mantenimiento', to='app.vehiculo')),
            ],
            options={
                'db_table': 'detalle_mantenimiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('state', models.IntegerField(choices=[(1, 'Activa'), (2, 'Finalizada'), (3, 'Pendiente'), (4, 'Cancelada')], default=1)),
                ('id_conductor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asignaciones', to='app.conductor')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asignaciones', to='app.vehiculo')),
            ],
            options={
                'db_table': 'asignacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AlertaMantenimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=250)),
                ('fecha_alerta', models.DateField()),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='alertas_mantenimiento', to='app.vehiculo')),
            ],
            options={
                'db_table': 'alerta_mantenimiento',
                'ordering': ['id'],
            },
        ),
    ]
