# Generated by Django 5.2 on 2025-04-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('id_rol', models.CharField(max_length=60)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Pendiente'), (4, 'Suspendido')], default=1)),
            ],
        ),
    ]
