# Generated by Django 5.2.1 on 2025-05-24 07:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=100)),
                ('doc_identity', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('licence_drive', models.CharField(max_length=30)),
                ('date_entry', models.DateField(default=django.utils.timezone.now)),
                ('state', models.IntegerField(choices=[(1, 'Disponible'), (2, 'No Disponible'), (3, 'De baja'), (4, 'Suspendido')], default=1)),
            ],
            options={
                'db_table': 'conductor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'tipo_mantenimiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'tipo_vehiculo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('id_rol', models.IntegerField(choices=[(1, 'Conductor'), (2, 'Tecnico'), (3, 'Admin')], default=3)),
                ('state', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Pendiente'), (4, 'Suspendido')], default=1)),
                ('last_date_support', models.DateField(blank=True, null=True)),
                ('next_date_support', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('marca', models.CharField(max_length=25)),
                ('modelo', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('state', models.IntegerField(choices=[(1, 'Nuevo'), (2, 'Deteriorado'), (3, 'Usado'), (4, 'Reparado')], default=1)),
                ('current_kilometers', models.FloatField(default=0)),
                ('last_date_support', models.DateField(blank=True, null=True)),
                ('next_date_support', models.DateField(blank=True, null=True)),
                ('id_tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vehiculos', to='app.tipovehiculo')),
            ],
            options={
                'db_table': 'vehiculo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServicioMantenimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='servicios_mantenimiento', to='app.vehiculo')),
            ],
            options={
                'db_table': 'servicio_mantenimiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('kilometraje', models.FloatField()),
                ('costo', models.FloatField()),
                ('workshop', models.CharField(max_length=100)),
                ('tipo', models.IntegerField(choices=[(1, 'Preventivo'), (2, 'Correctivo'), (3, 'General')], default=1)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('km_programado', models.FloatField(blank=True, null=True)),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mantenimientos', to='app.vehiculo')),
            ],
            options={
                'db_table': 'mantenimiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMantenimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.mantenimiento')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.serviciomantenimiento')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_mantenimiento', to='app.vehiculo')),
            ],
            options={
                'db_table': 'detalle_mantenimiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('state', models.IntegerField(choices=[(1, 'Activa'), (2, 'Finalizada'), (3, 'Pendiente'), (4, 'Cancelada')], default=1)),
                ('id_conductor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asignaciones', to='app.conductor')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asignaciones', to='app.vehiculo')),
            ],
            options={
                'db_table': 'asignacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AlertaMantenimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=250)),
                ('fecha_alerta', models.DateField()),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='alertas_mantenimiento', to='app.vehiculo')),
            ],
            options={
                'db_table': 'alerta_mantenimiento',
                'ordering': ['id'],
            },
        ),
    ]
