# Generated by Django 5.2 on 2025-04-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
