# Generated by Django 5.2.1 on 2025-05-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Preventivo'), (2, 'Correctivo')], default=1),
        ),
    ]
