# Generated by Django 5.2.1 on 2025-05-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='state',
            field=models.IntegerField(choices=[(1, 'Nuevo'), (2, 'Deteriorado'), (3, 'Usado'), (4, 'Reparado')], default=1),
        ),
    ]
