# Generated by Django 5.2.1 on 2025-05-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='doc_identity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='licence_drive',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='state',
            field=models.IntegerField(choices=[(1, 'Disponible'), (2, 'No Disponible'), (3, 'De baja'), (4, 'Suspendido')], default=1),
        ),
    ]
